[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = ""
  CONTENTFUL_ACCESS_TOKEN = ""
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = ""

[[redirects]]
  from = "/api/*"
  to = "https://maps.googleapis.com"
  status = 200
  force = true
  conditions = {Role = ["admin", "cms"]}
  [redirects.headers]
      X-From = "Netlify"
      X-Api-Key = GATSBY_GOGGLE_API_KEY

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"