[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = ""
  CONTENTFUL_ACCESS_TOKEN = ""
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = ""

[[redirects]]
  from = "/api/*"
  to = "https://deploy-preview-43--ornate-cranachan-4778da.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200